// send-email
//
// Drains public.email_outbox and sends each row through Brevo, then writes
// the outcome back. It is woken once a minute by drain_email_outbox(), which
// only pings when there is something queued.
//
// It is NOT a client endpoint. There is no user session involved: the caller
// proves itself with a shared secret that lives in Vault, and the same secret
// is read back here through the service role. Nothing privileged is in the
// client bundle and there is no dashboard secret to forget to set.
//
// One template for every email. A brand-new sending domain has no reputation,
// and heavy HTML is among the strongest signals spam filters weigh, so this is
// deliberately plain and text-led with a real text/plain alternative. Revisit
// in six months, not before.

import { createClient } from 'jsr:@supabase/supabase-js@2';

const BREVO_ENDPOINT = 'https://api.brevo.com/v3/smtp/email';

// ACC-9, decided 13 September: the sending address is
// volunteer@wellwindsor.org.uk. It is NOT the default here yet, on purpose —
// that sender is inactive in Brevo and the domain is unauthenticated, so
// switching now would break every email rather than none. Set
// BREVO_SENDER_EMAIL once the DNS records land and the sender is activated;
// do not edit this file to do it.
const SENDER_EMAIL = Deno.env.get('BREVO_SENDER_EMAIL') ?? 'thomascrone2000@gmail.com';
const SENDER_NAME = Deno.env.get('BREVO_SENDER_NAME') ?? 'Well Windsor';

// ACC-9, decided 13 September: replies to automated mail go to the charity's
// monitored inbox, so an organisation answering "I can't sign in" to a digest
// reaches a human. Unlike the sender, this does not wait on domain
// authentication — a Reply-To can be any address — so it is the default here
// rather than a secret to remember.
//
// A row may still override it: a problem report replies to whoever reported
// it. Outreach is not sent by this function at all; it replies to the
// organisation that wrote it.
const REPLY_TO_EMAIL = Deno.env.get('EMAIL_REPLY_TO') ?? 'hello@wellwindsor.org.uk';
const REPLY_TO_NAME = Deno.env.get('EMAIL_REPLY_TO_NAME') ?? SENDER_NAME;

// The site has no privacy policy yet — it is built in workflow 8. Pointing at
// a page that 404s is worse than pointing at the charity, so this defaults to
// the charity site and becomes the real URL by setting the secret.
const PRIVACY_URL = Deno.env.get('EMAIL_PRIVACY_URL') ?? 'https://www.wellwindsor.org.uk';

// An <img> whose URL does not resolve renders as a broken image in every mail
// client. The app is not hosted yet, so the mark is set as a word until there
// is a real absolute URL to give it.
const LOGO_URL = Deno.env.get('EMAIL_LOGO_URL') ?? '';

const BATCH = 25;
const MAX_ATTEMPTS = 5;

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** The one wrapper every email goes through. */
function wrap(bodyHtml: string): string {
  const mark = LOGO_URL
    ? `<img src="${esc(LOGO_URL)}" alt="Well Windsor" width="150" style="display:block;border:0;margin:0 0 24px">`
    : `<div style="font-size:17px;font-weight:700;letter-spacing:-0.01em;color:#0f766e;margin:0 0 24px">Well Windsor</div>`;

  return `<div style="font-family:system-ui,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;font-size:15px;line-height:1.6;color:#1f2937;max-width:560px;margin:0 auto;padding:8px">
${mark}
${bodyHtml}
<hr style="border:none;border-top:1px solid #e5e7eb;margin:28px 0 16px">
<p style="font-size:12px;line-height:1.55;color:#6b7280;margin:0">
Well Windsor connects volunteers with local organisations in Windsor.<br>
Registered charity number 1207021.
<a href="${esc(PRIVACY_URL)}" style="color:#6b7280">Privacy</a>
</p>
</div>`;
}

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

type Row = {
  id: string;
  template: string;
  to_email: string;
  to_name: string | null;
  reply_to_email: string | null;
  reply_to_name: string | null;
  subject: string;
  payload: Record<string, unknown>;
  attempts: number;
  related_user_id: string | null;
  related_record_id: string | null;
};

/** Returns [html, text] for a queued row. */
function render(row: Row): [string, string] {
  const p = row.payload ?? {};

  switch (row.template) {
    case 'org_approved': {
      const name = String(p.org_name ?? 'Your organisation');
      const html = wrap(
        `<p style="margin:0 0 16px">Hello ${esc(name)},</p>
<p style="margin:0 0 16px">Your Well Windsor account has been approved. You can now publish roles and contact volunteers who have registered interest.</p>
<p style="margin:0 0 16px">Sign in and post your first role whenever you are ready.</p>`,
      );
      const text =
        `Hello ${name},\n\n` +
        `Your Well Windsor account has been approved. You can now publish roles ` +
        `and contact volunteers who have registered interest.\n\n` +
        `Sign in and post your first role whenever you are ready.\n\n` +
        `---\nWell Windsor. Registered charity number 1207021.\n${PRIVACY_URL}`;
      return [html, text];
    }

    case 'org_awaiting': {
      const name = String(p.org_name ?? 'An organisation');
      const town = String(p.home_town ?? 'not given');
      const html = wrap(
        `<p style="margin:0 0 16px"><strong>${esc(name)}</strong> has signed up and is waiting for approval.</p>
<p style="margin:0 0 16px">Town: ${esc(town)}</p>
<p style="margin:0 0 16px">They cannot publish a role or contact anyone until an admin approves them on the Organisations tab.</p>`,
      );
      const text =
        `${name} has signed up and is waiting for approval.\n\n` +
        `Town: ${town}\n\n` +
        `They cannot publish a role or contact anyone until an admin approves ` +
        `them on the Organisations tab.\n\n` +
        `---\nWell Windsor. Registered charity number 1207021.`;
      return [html, text];
    }

    case 'problem_reported': {
      const report = String(p.report ?? '');
      const page = String(p.page_url ?? 'not recorded');
      const who = p.signed_in ? 'a signed-in account' : 'a signed-out visitor';
      const html = wrap(
        `<p style="margin:0 0 16px">A problem was reported from ${esc(who)}.</p>
<div style="padding:14px 16px;border-left:3px solid #d1d5db;background:#f9fafb;margin:0 0 16px;white-space:pre-wrap">${esc(report)}</div>
<p style="margin:0 0 16px;font-size:13px;color:#6b7280">Page: ${esc(page)}</p>
<p style="margin:0 0 16px">It is listed on the Reports tab of the admin dashboard, where it can be marked handled.</p>`,
      );
      const text =
        `A problem was reported from ${who}.\n\n${report}\n\n` +
        `Page: ${page}\n\n` +
        `It is listed on the Reports tab of the admin dashboard, where it can ` +
        `be marked handled.\n\n---\nWell Windsor. Registered charity number 1207021.`;
      return [html, text];
    }

    case 'digest': {
      const count = Number(p.count ?? 0);
      const items = Array.isArray(p.items) ? (p.items as Record<string, unknown>[]) : [];
      const rows = items
        .map((it) => {
          const note = String(it.note ?? '').trim();
          return `<li style="margin:0 0 12px">
<strong>${esc(it.volunteer_name)}</strong> &mdash; ${esc(it.role_title)}
${note ? `<div style="color:#4b5563;margin-top:2px">&ldquo;${esc(note)}&rdquo;</div>` : ''}
</li>`;
        })
        .join('');
      const html = wrap(
        `<p style="margin:0 0 16px">${count} ${plural(count, 'person has', 'people have')} registered interest in your roles.</p>
<ul style="margin:0 0 16px;padding-left:20px">${rows}</ul>
<p style="margin:0 0 16px">Sign in to read their profiles and write to the ones you would like to hear more from.</p>
<p style="margin:0 0 16px;font-size:13px;color:#6b7280">Contact details are not included here. You write to a volunteer through Well Windsor, and their reply comes straight to you.</p>`,
      );
      const text =
        `${count} ${plural(count, 'person has', 'people have')} registered interest in your roles.\n\n` +
        items
          .map((it) => {
            const note = String(it.note ?? '').trim();
            return `- ${it.volunteer_name} — ${it.role_title}${note ? `\n  "${note}"` : ''}`;
          })
          .join('\n') +
        `\n\nSign in to read their profiles and write to the ones you would like ` +
        `to hear more from.\n\nContact details are not included here.\n\n` +
        `---\nWell Windsor. Registered charity number 1207021.`;
      return [html, text];
    }

    case 'outreach_copy': {
      // CON-1: who, which role, a copy of the text. Never the volunteer's
      // address — that reaches the organisation only if they reply.
      const volunteer = String(p.volunteer_name ?? 'a volunteer');
      const role = p.role_title ? String(p.role_title) : '';
      const message = String(p.message ?? '');
      const about = role
        ? `about <strong>${esc(role)}</strong>`
        : 'about volunteering';
      const html = wrap(
        `<p style="margin:0 0 16px">Your message to <strong>${esc(volunteer)}</strong> ${about} has been sent.</p>
<div style="padding:14px 16px;border-left:3px solid #d1d5db;background:#f9fafb;margin:0 0 16px;white-space:pre-wrap">${esc(message)}</div>
<p style="margin:0 0 16px">If they reply, it will come straight to this address. You may not hear back from everyone.</p>`,
      );
      const text =
        `Your message to ${volunteer} ${role ? `about ${role}` : 'about volunteering'} has been sent.\n\n` +
        `${message}\n\n` +
        `If they reply, it will come straight to this address. You may not hear ` +
        `back from everyone.\n\n---\nWell Windsor. Registered charity number 1207021.`;
      return [html, text];
    }

    default: {
      const html = wrap(`<p style="margin:0">${esc(row.subject)}</p>`);
      return [html, row.subject];
    }
  }
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const admin = createClient(supabaseUrl, serviceKey);

  // --- Who is calling? -------------------------------------------------
  // The secret lives in Vault and is compared INSIDE the database, so it
  // never leaves Postgres. Reading vault.decrypted_secrets from here does
  // not work and fails closed: PostgREST only exposes the schemas it is
  // configured with, and `vault` is not one of them.
  const presented = req.headers.get('x-email-hook-secret') ?? '';
  const { data: ok, error: secretErr } = await admin.rpc('verify_email_hook_secret', {
    p_secret: presented,
  });

  if (secretErr || ok !== true) {
    return new Response(JSON.stringify({ error: 'Not authorised' }), { status: 401 });
  }

  const brevoKey = Deno.env.get('BREVO_KEY');
  if (!brevoKey) {
    console.error('BREVO_KEY is not set');
    return new Response(JSON.stringify({ error: 'Email is not configured' }), { status: 500 });
  }

  // --- Drain ------------------------------------------------------------
  const { data: rows, error: readErr } = await admin
    .from('email_outbox')
    .select('*')
    .eq('status', 'queued')
    .order('created_at', { ascending: true })
    .limit(BATCH);

  if (readErr) {
    console.error('could not read outbox', readErr);
    return new Response(JSON.stringify({ error: 'Could not read the outbox' }), { status: 500 });
  }

  let sent = 0;
  let failed = 0;

  for (const row of (rows ?? []) as Row[]) {
    const [htmlContent, textContent] = render(row);
    let providerMessageId: string | null = null;
    let sendError: string | null = null;

    // A row's own reply-to wins; otherwise the configured one, if any.
    const replyEmail = row.reply_to_email ?? (REPLY_TO_EMAIL || null);
    const replyName = row.reply_to_email ? row.reply_to_name ?? undefined : REPLY_TO_NAME;

    try {
      const res = await fetch(BREVO_ENDPOINT, {
        method: 'POST',
        headers: {
          'api-key': brevoKey,
          'content-type': 'application/json',
          accept: 'application/json',
        },
        body: JSON.stringify({
          sender: { name: SENDER_NAME, email: SENDER_EMAIL },
          to: [{ email: row.to_email, name: row.to_name ?? undefined }],
          ...(replyEmail ? { replyTo: { email: replyEmail, name: replyName } } : {}),
          subject: row.subject,
          htmlContent,
          textContent,
        }),
      });

      if (!res.ok) {
        sendError = `Brevo ${res.status}: ${(await res.text()).slice(0, 400)}`;
      } else {
        const payload = await res.json().catch(() => ({}));
        providerMessageId = payload?.messageId ?? null;
      }
    } catch (e) {
      sendError = `Request failed: ${e instanceof Error ? e.message : String(e)}`;
    }

    const attempts = (row.attempts ?? 0) + 1;

    if (sendError) {
      failed++;
      // Give up eventually rather than retrying a bad address once a minute
      // forever. An abandoned row keeps its error for anyone asking why.
      await admin
        .from('email_outbox')
        .update({
          status: attempts >= MAX_ATTEMPTS ? 'abandoned' : 'queued',
          attempts,
          last_error: sendError,
        })
        .eq('id', row.id);
    } else {
      sent++;
      await admin
        .from('email_outbox')
        .update({
          status: 'sent',
          attempts,
          sent_at: new Date().toISOString(),
          provider_message_id: providerMessageId,
          last_error: null,
        })
        .eq('id', row.id);
    }

    // "Did they get it?" has to be answerable from the log, not only from
    // this table.
    await admin.rpc('record_audit_event', {
      p_action_type: sendError ? 'email_failed' : 'email_sent',
      p_actor_kind: 'system',
      p_target_user_id: row.related_user_id,
      p_target_table: 'email_outbox',
      p_target_record_id: row.id,
      p_metadata: {
        template: row.template,
        provider_message_id: providerMessageId,
        error: sendError ? sendError.slice(0, 300) : null,
      },
    });
  }

  return new Response(JSON.stringify({ ok: true, sent, failed }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
});
